name: stevenwieland
favicon: null
layout_spectrum: 0.77967
typography_spectrum: 0.57607
title: Steven Wieland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27752f'
    - '#445660'
    - '#000000'
    - '#005500'
    - '#008000'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
