name: stevenwieland
favicon: null
layout_spectrum: 0.4906
typography_spectrum: 0.67002
title: Steven Wieland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27752f'
    - '#445660'
    - '#000000'
    - '#005500'
    - '#008000'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
