name: stevenwieland
favicon: null
layout_spectrum: 0
typography_spectrum: 0.95051
title: Steven Wieland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#28752f'
    - '#184471'
    - '#598961'
    - '#79a57e'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
